[package]
name = "webserver"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.9.11+spec-1.1.0"
serde = { version = "1.0.228", features = ["derive"] }
regex = "1.12.2"
ratatui = "0.30.0"
crossterm = "0.29.0"
log = "0.4.29"
